words:
  - antialiasing
  - autocorrect
  - bashmarks
  - cachix
  - checkjobs
  - checkwinsize
  - cleartype
  - defterm
  - dircolors
  - direnv
  - dotenv
  - enableexit
  - extglob
  - ghcman
  - ghcup
  - gnumake
  - histappend
  - ignoreboth
  - ignoreeof
  - iohk
  - jsonfmt
  - kakkun
  - karabiner
  - kazuki
  - lastexitcode
  - lessopen
  - lesspipe
  - libpam
  - mktemp
  - msys
  - netrc
  - nixfmt
  - nixos
  - nixpkgs
  - nocaseglob
  - nofork
  - npiperelay
  - numtide
  - Okamoto
  - pinentry
  - pkgs
  - poshdotenv
  - psake
  - psscriptanalyzer
  - pueue
  - pwsh
  - pythonioencoding
  - ricty
  - setsid
  - shellcheck
  - shlvl
  - showdirtystate
  - socat
  - sshell
  - stdenv
  - substituters
  - thefuck
  - treefmt
  - xcape
useGitignore: true
ignorePaths:
  - .cspell.json
  - .editorconfig
  - .git
  - .gitmodules
  - aqua-skk/kana-rule.conf
  - git/.gitconfig
  - lib
  - secret.yaml
enableGlobDot: true
