$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: 0.2
language: en
words:
  - ahci
  - antialiasing
  - aspmx
  - atproto
  - authelia
  - autocorrect
  - autogen
  - automount
  - avahi
  - awscli
  - bashmarks
  - bsky
  - btop
  - buildx
  - cachix
  - cfargotunnel
  - chcp
  - checkjobs
  - checkwinsize
  - cleartype
  - cloudflared
  - cloudnative
  - cnpg
  - cpuset
  - defterm
  - dircolors
  - direnv
  - distroless
  - dmarc
  - dmask
  - dnslink
  - domainkey
  - dotenv
  - doujin
  - earthdistance
  - enableexit
  - errexit
  - esac
  - extglob
  - fmask
  - frontmost
  - ghcman
  - ghcup
  - gnumake
  - goarch
  - goarm
  - googlecode
  - googledomains
  - googlehosted
  - hatenablog
  - histappend
  - ignoreboth
  - ignoreeof
  - immich
  - initdb
  - inputmethod
  - iohk
  - iterm
  - jsonfmt
  - kakkun
  - karabiner
  - kazuki
  - kubernetescrd
  - lastexitcode
  - lessopen
  - lesspipe
  - libpam
  - macskk
  - maihama
  - mdns
  - miniflux
  - mixi
  - mktemp
  - mrmn
  - msys
  - mtgto
  - netrc
  - networkmanager
  - nixd
  - nixfmt
  - nixos
  - nixpkgs
  - nocaseglob
  - nofail
  - nofork
  - nonroot
  - NOPASSWD
  - npiperelay
  - nssmdns
  - numtide
  - nvme
  - okamoto
  - pdfding
  - pids
  - pinentry
  - pipefail
  - pkgs
  - popd
  - poshdotenv
  - psake
  - psscriptanalyzer
  - pueue
  - pushd
  - pwsh
  - pythonioencoding
  - resolv
  - ricty
  - sdhci
  - setsid
  - setw
  - shellcheck
  - shlvl
  - showdirtystate
  - signup
  - socat
  - spacebar
  - squarespace
  - sshell
  - sslmode
  - stdenv
  - substituters
  - syncthing
  - tailnet
  - tensorchord
  - thefuck
  - traefik
  - treefmt
  - usbhid
  - usbip
  - valkey
  - vchord
  - vectorchord
  - vfat
  - virtualisation
  - vxlan
  - websecure
  - xcape
  - xhci
  - xtrace
  - yamls
  - zstd
useGitignore: true
ignoreWords:
  - fddo5yuqduqu
  - ldflags
  - skajdjtjjzil7b
  - wergwcbwqpv
  - 6BLKZ4X
  - 4MXV2IS
  - FOGMCRQ
  - AU7ALUP
  - IMAEGTP
  - 65G6OB3
  - LJ46OVA
  - BT5JQQH
ignoreRegExpList:
  - "[a-zA-Z0-9]{15,}"
ignorePaths:
  - .cspell.yaml
  - .editorconfig
  - .git
  - .gitignore
  - .gitmodules
  - coding-agent
  - home/aqua-skk
  - home/git/.gitconfig
  - home/karabiner
  - home/lib
  - home/mac-skk
enableGlobDot: true
