PWSH=pwsh

PSSCRIPTANALYZER_ENABLEEXIT= # -EnableExit

.PHONY: lint
lint: pwsh.lint

.PHONY: pwsh.lint
pwsh.lint:
	$(PWSH) -Command "Invoke-ScriptAnalyzer $(PSSCRIPTANALYZER_ENABLEEXIT) -Path .\pwsh\lib.ps1"
	$(PWSH) -Command "Invoke-ScriptAnalyzer $(PSSCRIPTANALYZER_ENABLEEXIT) -Path .\pwsh\profile.example.ps1"

spell:
	npm run cspell
