.PHONY: all
all: \
	direnv/direnv.toml \
	gh/config.yml \
	git/config \
	git/ignore \
	pueue/pueue.yml \
	tmux/tmux.conf

direnv/%: result/home-files/.config/direnv/% .out/autogen-note.txt
	@mkdir -p $(@D)
	cat .out/autogen-note.txt $< > $@

gh/%: result/home-files/.config/gh/% .out/autogen-note.txt
	@mkdir -p $(@D)
	cat .out/autogen-note.txt $< > $@

git/%: result/home-files/.config/git/% .out/autogen-note.txt
	@mkdir -p $(@D)
	cat .out/autogen-note.txt $< > $@

pueue/%: result/home-files/.config/pueue/% .out/autogen-note.txt
	@mkdir -p $(@D)
	cat .out/autogen-note.txt $< > $@

tmux/%: result/home-files/.config/tmux/% .out/autogen-note.txt
	@mkdir -p $(@D)
	cat .out/autogen-note.txt $< > $@

.out/autogen-note.txt:
	@mkdir -p $(@D)
	echo '############################################' > $@
	echo '# This file is auto-generated by Makefile. #' >> $@
	echo '# Do not edit this file directly.          #' >> $@
	echo '############################################' >> $@
	echo '' >> $@

# [Note] result ディレクトリー以下を生成するレシピがないのはなぜ？
# Nix なので生成日が 1970-01-01 になり、常にビルドが走ってしまうため
# 下記を手動で実行しよう
#
# home-manager build --flake .
