apiVersion: v1
kind: Namespace
metadata:
  name: immich
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
  storageClassName: nfs-client
---
# /mnt/usb-raid/photos を /external-library にマウントするための PersistentVolume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-external-library-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  nfs:
    path: /mnt/usb-raid/photos
    server: gmk.local.kakkun61.com
---
# /mnt/usb-raid/photos を /external-library にマウントするための PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-external-library
  namespace: immich
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: nfs-client
  volumeName: immich-external-library-pv
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: database
  namespace: immich
spec:
  instances: 1
  storage:
    storageClass: local-path
    size: 1Gi
  affinity:
    nodeSelector:
      kubernetes.io/hostname: gmk
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16.9-0.4.3
  postgresql:
    shared_preload_libraries:
      - "vchord.so"
  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: database-auth
      postInitApplicationSQL:
        # Commands based on: https://immich.app/docs/administration/postgres-standalone/#without-superuser-permission
        - CREATE EXTENSION vchord CASCADE;
        - CREATE EXTENSION earthdistance CASCADE;
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: immich-upload-size
  namespace: immich
spec:
  # 参考：https://baerentsen.space/immich-issue/
  buffering:
    maxRequestBodyBytes: 0 # 制限を無効化
    maxResponseBodyBytes: 0
    memRequestBodyBytes: 20971520
    memResponseBodyBytes: 20971520
    retryExpression: "IsNetworkError() && Attempts() < 2"
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: immich
  namespace: kube-system
spec:
  chart: oci://ghcr.io/immich-app/immich-charts/immich
  version: "0.13.1"
  targetNamespace: immich
  valuesContent: |-
