# See https://github.com/immich-app/immich-charts/blob/main/charts/immich/values.yaml

controllers:
  main:
    containers:
      main:
        image:
          tag: "v3.1.0"
        env:
          TZ: "Asia/Tokyo"
          DB_HOSTNAME: database-rw
          DB_USERNAME: immich
          DB_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: database-auth
                key: password

immich:
  persistence:
    library:
      existingClaim: immich-library

valkey:
  enabled: true
  persistence:
    data:
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClass: "nfs-client"

server:
  controllers:
    main:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: kubernetes.io/arch
                      operator: In
                      values:
                        - amd64
                        - arm64
  persistence:
    external-library:
      enabled: true
      type: persistentVolumeClaim
      existingClaim: immich-external-library
      advancedMounts:
        main:
          main:
            - path: /external-library
              readOnly: true
  ingress:
    main:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: immich-immich-upload-size@kubernetescrd
      hosts:
        - host: "immich.kakkun61.com"
          paths:
            - path: "/"
              service:
                identifier: main
        - host: "immich.local.kakkun61.com"
          paths:
            - path: "/"
              service:
                identifier: main

machine-learning:
  controllers:
    main:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: kubernetes.io/arch
                      operator: In
                      values:
                        - amd64
                        - arm64
