name: main

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: sudo apt install shellcheck
    - run: make SHELLCHECK_SEVERITY=warning PSSCRIPTANALYZER_ENABLEEXIT='-EnableExit'
